<a href="https://colab.research.google.com/github/Madathanapalleleena/DL_exploration/blob/main/dl_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

week 4

In [1]:
import tensorflow as tf
import numpy as np

# XOR Dataset
X = np.array([[0,0],[0,1],[1,0],[1,1]], dtype=np.float32)
y = np.array([[0],[1],[1],[0]], dtype=np.float32)

# Function to create a simple XOR MLP
def create_xor_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(4, activation='relu', input_dim=2),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])
    return model

# List of optimizers (Types of Gradient Descent)
optimizers = {
    'BGD (SGD default batch)': tf.keras.optimizers.SGD(learning_rate=0.1),  # Full batch
    'SGD': tf.keras.optimizers.SGD(learning_rate=0.1),
    'SGD with Momentum': tf.keras.optimizers.SGD(learning_rate=0.1, momentum=0.9),
    'SGD with Nesterov': tf.keras.optimizers.SGD(learning_rate=0.1, momentum=0.9, nesterov=True),
    'Adagrad': tf.keras.optimizers.Adagrad(learning_rate=0.1),
    'RMSProp': tf.keras.optimizers.RMSprop(learning_rate=0.01),
    'Adadelta': tf.keras.optimizers.Adadelta(learning_rate=1.0),
    'Adam': tf.keras.optimizers.Adam(learning_rate=0.01)
}

# Training loop for all optimizers
for name, opt in optimizers.items():
    print(f"\nTraining with optimizer: {name}")

    model = create_xor_model()
    model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

    # For simplicity, use full dataset in each epoch (small dataset)
    history = model.fit(X, y, epochs=500, verbose=0, batch_size=4)

    # Predictions
    preds = model.predict(X)
    print("Predictions:")
    print(np.round(preds, 2))

    # Final loss and accuracy
    loss, acc = model.evaluate(X, y, verbose=0)
    print(f"Final Loss: {loss:.4f}, Accuracy: {acc:.2f}")



Training with optimizer: BGD (SGD default batch)


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step
Predictions:
[[0.63]
 [0.63]
 [0.63]
 [0.06]]
Final Loss: 0.4956, Accuracy: 0.75

Training with optimizer: SGD
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 240ms/step
Predictions:
[[0.5 ]
 [0.97]
 [0.5 ]
 [0.04]]
Final Loss: 0.3638, Accuracy: 0.75

Training with optimizer: SGD with Momentum
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
Predictions:
[[0.01]
 [1.  ]
 [1.  ]
 [0.01]]
Final Loss: 0.0036, Accuracy: 1.00

Training with optimizer: SGD with Nesterov
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
Predictions:
[[0.67]
 [0.67]
 [0.67]
 [0.  ]]
Final Loss: 0.4776, Accuracy: 0.75

Training with optimizer: Adagrad


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
Predictions:
[[0.09]
 [0.98]
 [0.98]
 [0.01]]
Final Loss: 0.0340, Accuracy: 1.00

Training with optimizer: RMSProp


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
Predictions:
[[0.5]
 [1. ]
 [0.5]
 [0. ]]
Final Loss: 0.3466, Accuracy: 0.75

Training with optimizer: Adadelta
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
Predictions:
[[0.52]
 [0.52]
 [0.52]
 [0.44]]
Final Loss: 0.6535, Accuracy: 0.75

Training with optimizer: Adam
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
Predictions:
[[0.5 ]
 [0.99]
 [0.5 ]
 [0.01]]
Final Loss: 0.3502, Accuracy: 0.75


week 5

In [2]:
import tensorflow as tf
import numpy as np

# XOR Dataset
X = np.array([[0,0],[0,1],[1,0],[1,1]], dtype=np.float32)
y = np.array([[0],[1],[1],[0]], dtype=np.float32)

# Base Model
def create_base_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(4, activation='relu', input_dim=2),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

model = create_base_model()
history = model.fit(X, y, epochs=500, verbose=0)
print("Base model predictions:")
print(model.predict(X))

Base model predictions:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[[0.45153472]
 [0.5828004 ]
 [0.5441776 ]
 [0.4308024 ]]


In [8]:
#L2
from tensorflow.keras import regularizers

model_l2 = tf.keras.Sequential([
    tf.keras.layers.Dense(4, activation='relu',
                          input_dim=2,
                          kernel_regularizer=regularizers.l2(0.01)),
    tf.keras.layers.Dense(1, activation='sigmoid', kernel_regularizer=regularizers.l2(0.01))
])

model_l2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
history_l2 = model_l2.fit(X, y, epochs=500, verbose=0)
print("L2 model predictions:")
print(model_l2.predict(X))

L2 model predictions:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
[[0.4904422 ]
 [0.7225971 ]
 [0.49990568]
 [0.37757093]]


In [6]:
X_aug = X + np.random.normal(0, 0.05, X.shape)
y_aug = y

model_aug = create_base_model()
model_aug.fit(X_aug, y_aug, epochs=500, verbose=0)
print("Dataset augmentation predictions:")
print(model_aug.predict(X))

Dataset augmentation predictions:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
[[0.45266715]
 [0.58147734]
 [0.5433159 ]
 [0.4543936 ]]


In [7]:
model_noise = tf.keras.Sequential([
    tf.keras.layers.GaussianNoise(0.1, input_shape=(2,)),
    tf.keras.layers.Dense(4, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model_noise.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model_noise.fit(X, y, epochs=500, verbose=0)
print("Noise-added input predictions:")
print(model_noise.predict(X))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/regularization/gaussian_noise.py:29: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Noise-added input predictions:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step
[[0.34950408]
 [0.4617755 ]
 [0.7250913 ]
 [0.4617755 ]]


In [3]:
early_stop = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=20)

model_early = create_base_model()
model_early.fit(X, y, epochs=500, verbose=0, callbacks=[early_stop])
print("Early stopping predictions:")
print(model_early.predict(X))

Early stopping predictions:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[[0.45927316]
 [0.5412381 ]
 [0.45490494]
 [0.5368644 ]]


In [4]:
model_dropout = tf.keras.Sequential([
    tf.keras.layers.Dense(8, activation='relu', input_dim=2),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model_dropout.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model_dropout.fit(X, y, epochs=500, verbose=0)
print("Dropout predictions:")
print(model_dropout.predict(X))

Dropout predictions:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
[[0.46532473]
 [0.5825152 ]
 [0.51709306]
 [0.47448495]]


In [5]:
models = [create_base_model() for _ in range(5)]
for m in models:
    m.fit(X, y, epochs=500, verbose=0)

# Average predictions
preds = np.mean([m.predict(X) for m in models], axis=0)
print("Ensemble predictions:")
print(preds)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
Ensemble predictions:
[[0.50569886]
 [0.53388107]
 [0.5577346 ]
 [0.40888897]]
